//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendrier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionId { get; set; }
        public string Titre { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<byte> Duree { get; set; }
        public Nullable<int> Inscrits { get; set; }
    }
}
